name: Docker Compose Actions Workflow
on:
  push:
    branches:
        - main
    paths:
      - '**Dockerfile'
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
          
      - name: Push to docker hub
        run: docker compose push
