name: Docker Compose Actions Workflow
on:
  workflow_dispatch:
    
  push:
    branches:
        - main
    paths:
      - 'grafana/**'
      - 'parsedmarc/**'
      - 'python_docker/**'
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
          
      - name: Push to docker hub
        run: docker compose push

  docker_scan:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2     

      - name: Trivy - parsedmarc
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fraserc182/parsedmarc:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          
      - name: Trivy - grafana
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fraserc182/grafana:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          
      - name: Trivy - python_docker
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fraserc182/python_docker:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'          
