name: Docker Compose Actions Workflow
on:
  workflow_dispatch:
    
  push:
    branches:
        - main
    paths:
      - 'grafana/**'
      - 'parsedmarc/**'
      - 'python_docker/**'
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
          
      - name: Push to docker hub
        run: docker compose push

  docker_scan:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Pull and scan parsedmarc
        uses: azure/container-scan@v0
        with:
          image-name: parsedmarc:latest

      - name: Pull and scan grafana
        uses: azure/container-scan@v0
        with:
          image-name: grafana:latest

      - name: Pull and scan python_docker
        uses: azure/container-scan@v0
        with:
          image-name: python_docker:latest
